namespace _16nar.data;

attribute "narengine_prop";

/// @brief Header of the asset file.
struct FileHeader
{
     version:  uint32;
     size:     uint32;
}


/// @brief Data of the asset.
table AssetData
{
     type_id:  uint64;
     data:     [ubyte]   (required);
}


/// @brief Container with data and child containers.
table Asset
{
     name:     string    (key);
     is_array: bool = false;
     content:  AssetData;
     children: [Asset];
}


/// @brief Hash of a resource.
struct Hash
{
     name:     uint64;
     type_id:  uint64;
}


/// @brief Identifier of resource.
/// @details Usually, only one of the fields is set, either hash or name.
table ResourceId
{
     hash:     Hash;
     name:     string;
}


root_type Asset;
