namespace _16nar.data;

/// @brief 2-dimensional vector of floats.
struct Vec2f
{
     data:     [float32: 2];
}


/// @brief 2-dimensional vector of integers.
struct Vec2i
{
     data:     [int32: 2];
}


/// @brief 3-dimensional vector of floats.
struct Vec3f
{
     data:     [float32: 3];
}


/// @brief 3-dimensional vector of integers.
struct Vec3i
{
     data:     [int32: 3];
}


/// @brief 4-dimensional vector of floats.
struct Vec4f
{
     data:     [float32: 4];
}


/// @brief 4-dimensional vector of integers.
struct Vec4i
{
     data:     [int32: 4];
}


/// @brief Simple rectangle of integer type.
struct IntRect
{
     pos:      [int32: 2];
     end:      [int32: 2];
}


/// @brief Simple rectangle of float type.
struct FloatRect
{
     pos:      [float32: 2];
     end:      [float32: 2];
}


/// @brief Transformation matrix.
struct TransformMatrix
{
     data:     [float32: 16];
}


/// @brief Resource identifier within one file.
struct ResourceId
{
     package:  uint16;
     name:     uint16;
}


/// @brief Key-value properties containing payload.
table Properties
{
     data:               [ubyte]   (flexbuffer, required);
     unordered_data:     [ubyte]   (flexbuffer);
}


/// @brief Data satisfying specified schema.
table DataObject
{
     schema:   ResourceId     (required);
     props:    Properties     (required);
}


/// @brief List of dependencies' names from a package with package name.
table PackageDeps
{
     name:     string    (required);
     elements: [string]  (required);
}
