include "constructor2d_nodes.fbs";

namespace _16nar.data.constructor2d;

/// @brief Type of render system.
enum RenderSystemType
{
     QTreeRenderSystem
}


/// @brief Common render system information.
table RenderSystemData
{
     type:     RenderSystemType;
     data:     [ubyte]   (flexbuffer, required);
}


/// @brief Record about one state of the scene.
table SceneState2D
{
     updating:      bool;
     rendering:     bool;
     render_system: RenderSystemData    (required);
     nodes:         [NodeData]          (required);
}


/// @brief Scene executed by engine.
table Scene2D
{
     version:            uint32;
     deps:               Dependencies   (required);
     states:             [SceneState2D] (required);
     internal_pieces:    [ScenePiece2D] (optional);
     loop_func:          ResourceId     (optional);
     setup_func:         ResourceId     (optional);
}

root_type Scene2D;
file_identifier "16C2";  // 16nar engine, constructor 2D architecture
file_extension "nar";
