include "common.fbs";

namespace _16nar.data.constructor2d;

/// @brief Type of node on the scene.
enum NodeType
{
     Node2D,
     SpriteNode
}


/// @brief Common node information.
table NodeData
{
     type:     NodeType;
     props:    Properties     (required);
     ext:      [DataObject]   (optional);
}


/// @brief Lists of scene or scene piece dependencies.
table Dependencies
{
     resources:     [PackageDeps]  (required);
     libs:          [PackageDeps]  (required);
     pieces:        [PackageDeps]  (required);
}


/// @brief Record about reusable subtree of the scene.
table ScenePiece2D
{
     nodes:    [NodeData]     (required);
}
