macro(narengine_set_option var default opt_type docstring)
    if(NOT DEFINED "${var}")
        set("${var}" ${default})
    endif()
    set("${var}" ${${var}} CACHE "${opt_type}" "${docstring}" FORCE)
endmacro()


macro(narengine_add_deps target_name var_prefix)
    if(NOT "${${var_prefix}_COMPILER_DEFS}" STREQUAL "")
        target_compile_definitions("${target_name}" ${${var_prefix}_COMPILER_DEFS})
    endif()
    if(NOT "${${var_prefix}_INCLUDE_DIRS}" STREQUAL "")
        target_include_directories("${target_name}" ${${var_prefix}_INCLUDE_DIRS})
    endif()
    if(NOT "${${var_prefix}_LINK_DIRS}" STREQUAL "")
        target_link_directories("${target_name}" ${${var_prefix}_LINK_DIRS})
    endif()
    if(NOT "${${var_prefix}_LINK_LIBS}" STREQUAL "")
        target_link_libraries("${target_name}" ${${var_prefix}_LINK_LIBS})
    endif()
endmacro()
