name: test-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "dev" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y xorg-dev
           libx11-xcb-dev libxcb-glx0-dev libxcb-render-util0-dev libxcb-xkb-dev
           libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev
           libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev
           libxcb-dri3-dev libxcb-cursor-dev libxcb-dri2-0-dev libxcb-dri3-dev
           libxcb-present-dev libxcb-composite0-dev libxcb-ewmh-dev libxcb-res0-dev
           libxcb-util-dev libxcb-util0-dev

    - name: Conan installation
      id: conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"

    - name: Create default Conan profile
      run: conan profile detect --force

    - name: Conan install dependencies
      run:  conan install .
            --settings=build_type=${{ env.BUILD_TYPE }}
            --build=missing

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
           -DBUILD_SHARED_LIBS=OFF -DNARENGINE_BUILD_TESTS=ON
           -DNARENGINE_RENDER_VULKAN=OFF ${{ matrix.cmake-extra-options }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
